FROM golang:1.25.0-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./

RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    go build -o gateway ./cmd/server

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/gateway .
COPY application.yml .
CMD ["./gateway"]

