spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/product_catalog}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: product-catalog-service

grpc:
  server:
    port: 9090

catalog:
  limits:
    default: 25
    max: 50

internal:
  security:
    internal-api-key: ${INTERNAL_API_KEY:super-secret-key}
    jwt-secret: ${JWT_SECRET:cute-secret}
    protected-methods:
      - "/CreateProduct"
      - "/UpdateStock"
      - "/CreateCategory"
